### ISSUE TITLE
terra-clinical-item-collection component

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-clinical#100]
# Issue Description
An Item Collection is a wrapper component to display data as either a table or list of items dependent on the relative container size. 

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Initially data is displayed in a tabular format that flexes the rendered component, but as the container is resized and the indicated breakpoint is hit, the display changes to shows the data as a list of items. The `terra-table` and `terra-clinical-item` react components will be utilized for displaying the data in these two ways.

Ultimately, the `terra-clinical-item-collection` component allows consumers to organize tabular data and ensure this data is readable as screen sizes become progressively smaller.

**Comment by emilyrohrbough** [comment]
Resolved in #91
