### ISSUE TITLE
Update space styling for Item-Displays in Clinical-Item-Collection

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-clinical#113]
# Issue Description
Fix line-height/margin/padding/vertical-aligment of Displays when presented in the table view of the Clinical Item Collection, so that all text “baselines” are aligned and icons and text all appear to look centered vertically when there is only one line of text content.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
All Text and icons, when there is only a single line of content, in the table view should appear visually "centered" or aligned to the same baseline.

## Current Behavior
Start and End Accessories (icons) correctly display vertically centered. The Clinical Item Displays (text) are correctly aligned top but when single line of text, they align too high visually (row height could be too tall) and icons, the basic displays, and the comments - all align to different visual baselines.

## Required Enhancement
Will resolve fix comment added in [PR #91](https://github.com/cerner/terra-clinical/pull/91)

**Comment by emilyrohrbough** [comment]
@neilpfeiffer PR https://github.com/cerner/terra-clinical/pull/104 should have fixed this issue. Can you check to see if this was resolved when you get a chance?

**Comment by neilpfeiffer** [comment]
@emilyrohrbough Excellent. Looks good!

Closing this issue as being resolved after merging [PR #104](https://github.com/cerner/terra-clinical/pull/104)
