### ISSUE TITLE
Item-View, icons do not scale

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-clinical#115]
# Issue Description

At larger font-sizes, icons get cropped off at the bottom. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Icons scaled with font-size.

## Current Behavior

Icons are not scaled with font-size.
![screen shot 2017-06-28 at 12 44 08 pm](https://user-images.githubusercontent.com/8146159/27652003-c4fd88d4-5bff-11e7-9141-9be9bd2a4b08.png)

The person, comment, and information icon are cropped off at the bottom. 

## Steps to Reproduce

1. Open the item-view examples
2. Adjust the browser font-size to very large.

## Environment

* Component Version: 0.2.0
* Browser Name and Version: Chrome 
* Operating System and version (desktop or mobile): v58

**Comment by emilyrohrbough** [comment]
> The person, comment, and information icon are cropped off at the bottom.

PR #156 should fix the current behavior seen with the person and comment being cut off.
