### ISSUE TITLE
Update DetailView to accept elements under subtitles

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-clinical#15]
We have a situation where we would like to provide an array of elements within the DetailView to display a series of Icons/Graphics under subtitles.

For items that need to retain multiple icons in
![image](https://cloud.githubusercontent.com/assets/1711642/25203346/8319aec4-251e-11e7-9079-253aff674dae.png)
the detail view, we would like to be able to list them in the "header" area like the attached image. 

We would like the DetailView's subtitles to take in elements, not just strings.

**Comment by neilpfeiffer** [comment]
Will be resolved by the PR created for #305
