### ISSUE TITLE
Header margin rtl

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-clinical#157]
# Issue Description

When dir=rtl, the header does not have margin between the button and the heading.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

There is margin between the button and the heading

## Current Behavior

![header_margin](https://user-images.githubusercontent.com/8146159/28339860-33aa25d4-6bd3-11e7-8cec-53b5b9849086.gif)

**Comment by emilyrohrbough** [comment]
That is interesting. I am seeing the correct margin being applied from prod site. 
<img width="937" alt="screen shot 2017-07-18 at 5 56 46 pm" src="https://user-images.githubusercontent.com/14099737/28343385-b7eff71a-6be2-11e7-8fb7-587198caa38a.png">

On the [initial pull request](https://github.com/cerner/terra-clinical/pull/147) for converting to css modules, it had appeared the styling was not being applied correctly. The discussion on the PR included screenshots of similar issues, however the next day the issues were no longer present.

**Comment by emilyrohrbough** [comment]
The Header component does not apply margins or padding on the startContent, endContent or title pieces. Further investigation shows the issue seen here is actually an issue with the padding being applied on the terra-button component.

<img width="1198" alt="screen shot 2017-07-19 at 10 43 37 am" src="https://user-images.githubusercontent.com/14099737/28376476-d138ed3e-6c6f-11e7-99f6-3d934f6b9b57.png">


<img width="1212" alt="screen shot 2017-07-19 at 10 43 56 am" src="https://user-images.githubusercontent.com/14099737/28376479-d5bb1bde-6c6f-11e7-87b7-ca2d6591c24c.png">

The terra-button component is applying both a right and left padding style and it seems the RTL plugin is not changing the initially applied padding.

<img width="281" alt="screen shot 2017-07-19 at 10 44 25 am" src="https://user-images.githubusercontent.com/14099737/28376554-05fbef62-6c70-11e7-9a76-e7a199608597.png">

**Comment by emilyrohrbough** [comment]
Logged Issued here: https://github.com/cerner/terra-core/issues/641

**Comment by jmsv6d** [comment]
@emilyrohrbough I don't think there's any issue in the button. The margin in the header example is applied inline the clinical-site header examples here: https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-site/src/examples/header/ContentHeader.jsx#L8

**Comment by emilyrohrbough** [comment]
@jmsv6d Didn't think to check the example styling. Looks like that was the issue.
