### ISSUE TITLE
React 16 upgrade

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-clinical#161]
# Issue Description
When react 16 comes out, we'll want to enable compatibility with react 16.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Terra components are compatible with React 16

## Current Behavior
N/A

**Comment by noahbenham** [comment]
Will any uplifts you perform be backwards compatible with consumers using React 15? We still have substantial work to do uplifting deprecated code.

**Comment by emilyrohrbough** [comment]
@noahbenham uplifts to use React 16 should remain compatible with React 15 as well.

**Comment by emilyrohrbough** [comment]
The React Team's progress in releasing v16 https://github.com/facebook/react/issues/10294

**Comment by emilyrohrbough** [comment]
### Third Party Dependencies Requiring React:

| Good To Go | Dependency | Current Specified Version | React 16 Supported Version | Watch Issue 
| ----|----|----|----|-----|
| BLOCKED | enzyme | v^2.8.2 | v^3.x |  |
| ✅  | react-intl | v^2.2.3 & v^2.3.0 | v2.4.0 | Need to bump to v2.4.0 |
| ✅  | react-redux | v^5.0.4 | v4.4.7 | N/A |
| ✅  | react-router | v^3.0.5 | v3.2.0  | Need to bump to v3.2.0 |
|  | react-modal | v^1.6.5  | N/A | https://github.com/reactjs/react-modal/issues/498 |
| Waiting on Confirmation | react-router-dom | v^4.0.0 | --- | https://github.com/ReactTraining/react-router/issues/5563  |

**Comment by emilyrohrbough** [comment]
This is blocked by:
- [ ] https://github.com/cerner/terra-clinical/issues/198
- [ ] Release of terra-core React 16 support.

**Comment by emilyrohrbough** [comment]
Upon checking the react-modal commit history, React 16 compatibility is available in v3.0, however, I noticed a message indicated  v4.0.0-beta.5 replaced PropTypes with the `prop-types` library. To ensure not warnings occur, we should bump to a minimum of v4.0.0.

**Comment by emilyrohrbough** [comment]
Unblocked by #198.  However will need to implement `enzyme-adapter-react-16`.
