### ISSUE TITLE
ItemView not truncating correctly in IE 10

### ISSUE THREAD

**Issue by hboege** [cerner/terra-clinical#196]
# Issue Description
Truncating works in most browsers, but not in IE 10.  (These seems like it might be a continuation of issue #148.)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
Truncate material in IE 10, just as it is done in other browsers.

## Current Behavior
On the [Item View All Elements](http://engineering.cerner.com/terra-clinical/#/site/item-view) example, the 3rd line of text ("Start Time"), the left-hand side text will truncate in most browsers.  In IE 10, the text is just cut off (i.e. no ellipsis).

## Steps to Reproduce
1. Go to http://engineering.cerner.com/terra-clinical/#/site/item-view on IE 10
2. Scroll to the bottom of the screen
3. Reduce the screen size as much as possible
4. See there is no truncation.

## Environment
* Component Version: 1.3.0
* Browser Name and Version: IE 10
* Operating System and version (desktop or mobile): PC laptop

**Comment by madelineisabelle** [comment]
After looking into this, it looks like the issue is width: 100% needing to be added to item display for truncation to work in IE10.
