### ISSUE TITLE
Item Display: add new styles

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-clinical#209]
# Issue Description
1. Need to add two new textStyles to Item Display:
   1a. that makes text bold but keeps current text color (not red).
   1b. an inactive version, superlight text 
2. Change the Item Comment icon color to use transparency (looks better when row is selected).

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Add two new options to the textStyle prop: 'bold'/'strong', and 'inactive'/'disabled' or similar wording for the props.

## Current Behavior
Item Display currently has {default}, 'secondary', 'attention', 'strikeThrough'.

**Comment by neilpfeiffer** [comment]
Will provide colors for styles needed.

**Comment by noahbenham** [comment]
@neilpfeiffer I'm happy to take this on if you're able to provide the color values.

**Comment by neilpfeiffer** [comment]
@noahbenham - 

After talking through the original designer's ask - I think we need to alter tech design from initial issue description to change from 'inactive'/'disabled' being an additional **`textStyle`** to a new prop **`isInvalid`** (default is false) with inactive styles for all textStyles, to better follow current API patterns of other components. 

----
### ItemDisplay.scss

.secondary { 
    ~~color: #64696c !important;~~ _/\*update\*/_
    color: #75767d !important;   
} 

.strong{ 
    font-weight: 700; 
}

.attention {
    color: #c00 !important;
    font-weight: 700 !important;
  }

.strike-through {
     text-decoration: line-through !important;
}

**_[ALL]_** &.inactive { opacity: 0.18 !important; }




----
### ItemComment.scss
.item-comment {
    @include terra-clinical-item-body;
    ~~color: #64696c;~~ _/\*update\*/_
    color: #75767d;
}

_/\*new: add for just the comment icon\*/_
**_[something like: .item-comment + . inline-icon]_** {
    color: rgba(117,118,125,0.30);
}

**Comment by noahbenham** [comment]
# Tech Design for Item Display
## Summary:
Introduce new bolded `textStyle` and `isInvalid` prop to allow better styling.
## Requirements:
N/A

## Requirements Added:
N/A

## Requirements Dropped:
N/A

## Responsiveness:
N/A

## Bidirectionality
N/A

## Accessibility
N/A

## React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| isInvalid | node | false    | Whether or not the text should be styled as invalid. |

## Example:
```jsx
<ItemDisplay
  text="display text"
  textStyle="attention"
  isTruncated
  isInvalid
  icon={<img alt="Graphic" />}
/>
```

## CSS Classes:
| Selector         | Description |
|------------------|-------------|
| .is-invalid | **New**. Opacity `0.18` |
| .is-invalid.inline-icon | **New**. Color `rgba(117, 118, 125, 0.3)` |
| .strong | **New**. Font weight `700` |
| .item-comment | Modify color to `#75767d` |
| . secondary | Modify color to `#75767d` |

**Comment by emilyrohrbough** [comment]
There is [this issue](https://github.com/cerner/terra-core/issues/1044) logged in terra-core to export prop options through the Utils object. Would you mind making that change here for the `textStyles` prop?

**Comment by emilyrohrbough** [comment]
After looking at this tech-design, seeing these styles and looking at the pull request, I'm not sure the prop `isInvalid` is the correct prop for the concept we are indicating. IMO, the term/prop `isDisabled` would better reflect and inactive style.

**Comment by noahbenham** [comment]
I agree with that assessment, @emilyrohrbough. I named it per @neilpfeiffer's suggestion, but would prefer to change it. Neil?
