### ISSUE TITLE
Item Collection: Add subheaders to the ItemCollection

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-clinical#216]
# Issue Description
Some consumers have expressed the need to have subheaders within the ItemCollection. With the coming updates to the ItemCollection API, this might be more possible.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Subheaders can be rendered between items in the item collection (similar to the list/table implementations).

## Current Behavior
Subheaders cannot be added through the prop-based API.

**Comment by emilyrohrbough** [comment]
@BenBoersma did you add an example to https://github.com/cerner/terra-clinical/pull/687 to show how to do this?

**Comment by BenBoersma** [comment]
Currently there isn't example on how to do this, but I can easily put one in.
