### ISSUE TITLE
Item View: Add Props to Handle Missing Accessory Alignment

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#217]
# Issue Description
Add additional props to add the appropriate spacing if an accessory is not present. 

For example, in the scenario that several Item Views with varying content are stacked underneath one anther, one would expect the displays to align, even if the content is not present. These props could be passed to handle this.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Allow ItemView to add the appropriate accessory spacing if there is no accessory and a bool prop is provided.
<img width="721" alt="screen shot 2017-10-26 at 9 16 39 am" src="https://user-images.githubusercontent.com/14099737/32057986-6eb639e8-ba2e-11e7-9f46-3e4b9527f5b9.png">

### Current Behavior 
<img width="737" alt="screen shot 2017-10-26 at 9 14 52 am" src="https://user-images.githubusercontent.com/14099737/32057904-30ff3866-ba2e-11e7-82dd-e352ad55ecdc.png">

**Comment by PaulSolDev** [comment]
Orion JIRA created

**Comment by tm4027** [comment]
JIRA created
