### ISSUE TITLE
Create enumeration for PropTypes.oneOf

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-clinical#234]
# Issue Description
For [any package](https://github.com/cerner/terra-clinical/search?utf8=%E2%9C%93&q=oneOf%28&type=) that has a prop with a type of PropTypes.oneOf, an enumerations should be made available for that prop to make it easier for consumers to know the acceptable values. This also minimizes consumers from making typos when setting these props. 

An example of of a prop using enumeration is [alert type](https://github.com/cerner/terra-core/blob/master/packages/terra-alert/src/Alert.jsx#L16-L24) in the Alert component.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

**Comment by emilyrohrbough** [comment]
Packages that need updated:

- [ ] terra-clinical-item-collection
- [ ] terra-item-display
- [ ] terra-item-view
