### ISSUE TITLE
[LabelValueView] Add support for pre-wrap text styling so whitespace is respected (user comments)

### ISSUE THREAD

**Issue by doogthemushroom** [cerner/terra-clinical#239]
# Issue Description
I'd like to be able to use LabelValueView's as a structure for user comments, but the text white-space styling needs to be `pre-wrap` so users can format comments using white-space. I would be willing to contribute this change.

white-space `normal`:
<img width="933" alt="normal" src="https://user-images.githubusercontent.com/1391996/33774724-ddac55c2-dc01-11e7-9c9b-558772e849cd.png">

white-space `pre-wrap`:
<img width="336" alt="pre-wrap" src="https://user-images.githubusercontent.com/1391996/33774738-e4e0ffa0-dc01-11e7-89e9-48d6043790b2.png">

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
A boolean prop with a default value of false can be set to true to enable the `pre-wrap` behavior. Prop name could be `isFormattedText`.

## Current Behavior
N/A

Again, I would be happy to contribute this.

**Comment by emilyrohrbough** [comment]
LabelValueView supports [children](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-label-value-view/src/LabelValueView.jsx#L21). With this option, you'd be able to format your text as desired without needed to change the component.

**Comment by doogthemushroom** [comment]
Hm yep that would do it. Thanks for the clarification @emilyrohrbough
