### ISSUE TITLE
Truncation Issues with SelectableList.Item with ItemView/ItemView.Display on IE

### ISSUE THREAD

**Issue by PseudoFaux** [cerner/terra-clinical#243]
# Issue Description

For our application, we utilize the SelectableList.Item with a Truncated ItemView as the content, with ItemView.Display as the displays.

-SelectableList.Item
--ItemView
---ItemView.Display

When the text is too large, the text _should_ truncate with the ellipsis, like so:
![image](https://user-images.githubusercontent.com/7713715/34392495-1772521a-eb12-11e7-9936-2f39ba4e5cb3.png)

However, in IE, it does not truncate:
![image](https://user-images.githubusercontent.com/7713715/34392509-2d049944-eb12-11e7-8b04-69ddc09da823.png)

**POTENTIAL FIX**
**It might be good to note that I was able to fix the issue by putting a**
`flex: 1 1 0px;`
**on the Arrange component generated by the ListItem component.**

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

In IE, when the text is too large, it should truncate with the ellipsis.

## Current Behavior

In IE, when the text is too large, it pushes the size of the container to the width of the longest text.

## Environment

* Component Version: 
terra-list : 1.17.0
terra-clinical-item-view : 1.5.1
terra-clinical-item-display : 1.5.0
* Browser Name and Version: Internet Explorer -> Any version of IE10/IE11(Edge)
* Operating System and version (desktop or mobile): Windows Desktop

**Comment by emilyrohrbough** [comment]
To add context to the issue being seen here:

**Steps to Produce:** This is SingleSelectable List that has ItemViews dropped into the ListItem's content. Then this SingleSelectable List is the main content within a Slide Panel which is being placed within a Modal. 

@PseudoFaux noted the visual was correct when `isTruncated={false}` was placed on the ItemViews, however it resulted in the following display when setting `isTruncate={true}`.

This leads me to believe this is truncation issue possibly similar to the one resolved in this PR: https://github.com/cerner/terra-clinical/pull/232.

![screen shot 2017-12-27 at 4 11 06 pm](https://user-images.githubusercontent.com/14099737/34394690-99cf42be-eb20-11e7-8934-b1aa564520de.png)

**Comment by PaulSolDev** [comment]
Functional review complete.  No issues identified.
