### ISSUE TITLE
Clean Up documentation for the ItemCollection

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-clinical#249]
# Issue Description
The Markdown example for the ItemCollection isn't a full working example. Consumers will be copying and pasting the code to use our packages, so it's recommended to rework the MD example to be a full working ItemCollection.

## Issue Type

- [ ] New Feature
- [] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
ItemCollection example code is complete

## Current Behavior
ItemCollection example has invalid tags like <Icon /> and takes like <IconDisplay /> that feel incomplete.

**Comment by emilyrohrbough** [comment]
Resolved in https://github.com/cerner/terra-clinical/pull/332
