### ISSUE TITLE
Deprecate Error and No Data Views

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-clinical#252]
# Issue Description
Deprecate terra-error-view and terra-no-data-view.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

## Expected Behavior
terra-error-view and terra-no-data-view are removed.  Have been replaced by the terra-status-view in the terra-core project.

**Comment by noahbenham** [comment]
Thanks for opening this, I was just about to consume Error View and will hold off in favor of Status View. When will `terra-status-view` be available on npm?

**Comment by ChaseSinclair** [comment]
@kschuste We are currently using the Error View for the new HealtheatCerner site [here](https://github.cerner.com/HealtheLife/healthe-at-cerner/blob/master/package.json#L54). Can we keep this from being deprecated?

**Comment by dm123455** [comment]
I am also curious why the search did not identify our repo!

**Comment by kschuste** [comment]
@ChaseSinclair you will still be able to use the error view, but it will still be deprecated, I would advise to switch to the terra-status-view in the terra-core repo when is released.

**Comment by mjhenkes** [comment]
oops didn't mean to close that
