### ISSUE TITLE
Fix padding in list view of ItemCollection

### ISSUE THREAD

**Issue by madelineisabelle** [cerner/terra-clinical#254]
# Issue Description
Currently, you are allowed to set isTablePadded to get padding on the table view of an ItemCollection. This padding does not carryover to the list view and makes everything seemed very squished.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
As there is padding on the table when isTablePadded is true, there should be padding on the list as well.

## Current Behavior
<img width="404" alt="screen shot 2018-01-22 at 4 52 59 pm" src="https://user-images.githubusercontent.com/8262756/35248952-ae265e80-ff95-11e7-96f6-9ed36bc02ba5.png">
<img width="1299" alt="screen shot 2018-01-22 at 4 52 48 pm" src="https://user-images.githubusercontent.com/8262756/35248953-ae3bca2c-ff95-11e7-894f-04dd72d57930.png">

## Steps to Reproduce
Create an ItemCollection with rows, add isTablePadded on the ItemCollection. In the large/table view, see the padding around the edges of each row. Shrink down to a list view, see how there is no padding around the edges of each row.

## Environment
* Component Version: 2.2.0
* Browser Name: Chrome
* Operating System and version (desktop or mobile): desktop

**Comment by ryanthemanuel** [comment]
@avinashg1994 we are actually planning on deprecating the item collection (https://github.com/cerner/terra-clinical/issues/464).  We realize there are many gaps in functionality that exist but the easiest way to manage that is for teams to create their own wrapper that switches between a list and table (which is also going under changes https://github.com/cerner/terra-core/issues/2195).  That is going to be our plan going forward.
