### ISSUE TITLE
Single column DetailView::DetailListItem

### ISSUE THREAD

**Issue by JoeJennings** [cerner/terra-clinical#255]
# Issue Description
Need single column DetailView::DetailListItems.  Perhaps a prop we can set on individual DetailListItems. We're creating a detail view that contains editable fields and the UX visuals have the editable fields in a single column:

![screen shot 2018-01-24 at 2 14 35 pm](https://user-images.githubusercontent.com/1821207/35355009-942648d8-0111-11e8-8a49-eef02b95d747.png)

We could hack around this and add custom styles but would prefer not too.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
As described in issue description

## Current Behavior
DetailView wraps up DetailListItems as space allows:
<img width="500" alt="screen shot 2018-01-24 at 3 06 31 pm" src="https://user-images.githubusercontent.com/1821207/35357159-5028d2d4-0118-11e8-8944-a2082739fa15.png">

**Comment by neilpfeiffer** [comment]
@JoeJennings I'll take a look at the design with Chelsea and come up with an enhancement /tech-design proposal to the team.
