### ISSUE TITLE
Uplift Onset Picker to utilize new Form Selects

### ISSUE THREAD

**Issue by doogthemushroom** [cerner/terra-clinical#256]
# Issue Description
Would like to see the current Onset Picker uplifted to use new Form Selects utilizing OCS. Would also like to see an option to change the default value from current date to unselected as well.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
I expect my form to look slick with OCS and this OnsetPicker is a real drag, man! Expect to use Form Select from terra-form-select.

## Current Behavior
Uses Select from terra-form.

**Comment by ryanthemanuel** [comment]
@doogthemushroom is going to pick this up.

**Comment by ryanthemanuel** [comment]
@doogthemushroom do we have an eta on when this will get done?  I think on 11/29, you said it was going to be out for a PR soon.

**Comment by ryanthemanuel** [comment]
Spoke with @doogthemushroom offline and he said he should have the PR out by EOD 12/3.

**Comment by doogthemushroom** [comment]
I think this can be closed as a result of #427
