### ISSUE TITLE
Label-Value-View TRVM visual fixes

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-clinical#258]
# Issue Description
Options:
1. Either provide minor updates to fix UI inconsistencies from TRVM uplifts to new Terra-UI/React. Looking for better match when using the  sizing/spacing of "Label" to look similar when inserting an Item-Display as "Node".

2. (OR) look at changing API to remove the label prop so that component only takes a node.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## UI Design Direction

**Label Color** - _doesn't pass AA contrast_ 
- Current: #909496
- Change to: #75767d

\
**Label Size** - _font size too big_ 
- Current: 1rem (14px)
- Change to: 0.8571428571rem (12px)

\
**Value Size (using text)** - _font size too big_ 
- Current: 1.428rem (20px)
- Change to: 1rem (14px)

\
**Values (using a Node)** - _margin/padding spacing_ 
- Check to make sure has same size/spacing if node is used vs. a value as text

**Comment by mjhenkes** [comment]
I marked this as a bug and removed the milestone to surface it again. It's a visual inconsistency problem with existing components.
