### ISSUE TITLE
Header start & end margins

### ISSUE THREAD

**Issue by noahbenham** [cerner/terra-clinical#264]
# Issue Description

Would it make sense to include default margins on either side of the left & right header content, or is that too restrictive to consumers?

I'd like to be able to just drop in text and buttons on either side but with the current design, it looks like this:

![screen shot 2018-01-31 at 12 25 45 pm](https://user-images.githubusercontent.com/6981195/35640122-e078b8d6-0681-11e8-926a-cb64b0312850.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Header adds margin between left/right content & text.

## Current Behavior

No margin is specified - even Terra examples do this manually to make things look okay.

## Environment

* Component Version: 1.7.0
* Browser Name and Version: N/A
* Operating System and version (desktop or mobile): N/A

**Comment by emilyrohrbough** [comment]
@noahbenham Do you have a gist of how you are composing the example of the screenshot provided? I am assuming you are dropping the content in as children?

**Comment by emilyrohrbough** [comment]
Oops. I was looking at the wrong component's src code.

**Comment by StephenEsser** [comment]
This is probably a good situation to use the Spacer component around the Button.

![image](https://user-images.githubusercontent.com/6720991/35642281-49f04242-0688-11e8-9702-eaff06fdf83d.png)

```
<Header
  title="Messages"
  startContent={<Spacer paddingRight="large"><Button icon={<IconList height="1em" width="1em" />} /></Spacer>}
  endContent={<Button icon={<IconPaperPencil height="1em" width="1em" />} />}
/>
```
https://github.com/cerner/terra-core/blob/master/packages/terra-spacer/docs/README.md

UX probably has more concrete feedback on this situation and may want to add padding in the future. My understanding was the content within the start and end accessories should be responsible for padding and margin. It's easier for additional content to add padding and margins than it is to be taken away if undesired.

**Comment by mjhenkes** [comment]
I'd argue we should have spacing built into this component. The spacer works, but this is a primary use case for this component, and by requiring use of the spacer component the spacing for the header won't be theme-able except at a broad level.

**Comment by emilyrohrbough** [comment]
When talking to @noahbenham I mentioned that the same as @StephenEsser, however given this component does not take children I also feel built-in spacing would be expected.

**Comment by neilpfeiffer** [comment]
I'll work with @noahbenham to provide the design input for a PR.
