### ISSUE TITLE
Accessing ActionHeader buttons from automated tests

### ISSUE THREAD

**Issue by hs025828** [cerner/terra-clinical#266]
# Issue Description
I'm writing automated tests for a component that uses an [ActionHeader](https://github.com/cerner/terra-clinical/tree/master/packages/terra-clinical-action-header) and I'd like to access the header buttons from within my test.  Normally, I would apply my own classes to the buttons and find them by class name, but because the buttons are created internally by the ActionHeader component there is no obvious way of applying my own classes to them.  I could access them by their index (as in, access the Nth `<button />`), but this is brittle - especially in my case where a buttons presence is variable.  What would be the recommended solution or possible enhancement for this issue?

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by JakeLaCombe** [comment]
If you would like to access the buttons from a test, my recommendation is to attach an ID to the buttons you are looking to write test code against, and then look for those when writing selectors for your test.

**Comment by JakeLaCombe** [comment]
I'm sorry. I thought that strategy would work. I was looking at the wrong repo. Let me rethink this.

**Comment by JakeLaCombe** [comment]
My other suggestion would be to use the aria-label attributes that are attached to the button. I've used that for testing time-picker buttons.

**Comment by hs025828** [comment]
@JakeLaCombe Thank you for the suggestion.  I'd like to attach aria-labels, classes, and what have you, but the ActionHeader component is creating the buttons internally.  I don't have a `ref` and/or way to assign my own properties to them.

**Comment by JakeLaCombe** [comment]
You don't have to attach your own labels. They are actually built with aria-label values. https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-action-header/src/ActionHeader.jsx#L107. You could write your selectors to match those values.

**Comment by hs025828** [comment]
@JakeLaCombe I gotcha.  Thanks, that does solve my issue.
