### ISSUE TITLE
Add Clinical Result View

### ISSUE THREAD

**Issue by jeffmerten** [cerner/terra-clinical#267]
# Issue Description
Add reusable view component currently called 'ClinicalResultView' that is used to show measurements such as labs and vitals in various views (grids/lists/stand alone).

![example crv](https://user-images.githubusercontent.com/34603098/35866518-029fcd10-0b1d-11e8-86bb-f75aacf219ed.PNG)

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by jeffmerten** [comment]
# Tech Design for Clinical Result View

## Summary:

The Clinical Result View is a small stateless view that is intended to show measurements such as labs and vitals. The view is designed in a way that it can handle a single measurement (such as weight), but also show paired measurements such as blood pressure. In a clinical setting, each measurement can have additional metadata associated on the result, like whether it's a critical value or has been modified, or even if it's an unexpected value.

It can be considered as a common visual representation of the [FHIR observation](https://www.hl7.org/fhir/observation.html).

## Bidirectionality:
Alignment will the mirrored in the right to left orientation

## Accessibility:
TBD

## React Props:

|Prop Name |Type  |Required| Default Value |Description | Example
|----------|------|------|------------|------------|--------------|
| results |array  | false | [] |An array of one or more results. Can be empty| [{ value: '50', unit: 'ml', normalcy: 'CRITICAL'}] |
| timeDisplay |string   | false | none |  A string for displaying the time of the measurement| "October 28, 2016 07:28" |
| hasDocument |bool | false| false | Whether the result has associated documents with it| "true" |
| hasComment |bool | false| false | Whether the result has associated comments with it| "true" |
| isModified |bool | false| false | Whether the result had a modification | "true" |
| align |string | false| alignStart | The alignment for the view | "alignStart" |
| isTruncated |bool | false| true | Whether the result values should allow truncation | "true" |
| isPadded |bool | false| false | Whether the view should be padded | "true" |

## Example:

```
const results = [{ value: '50', unit: 'ml', normalcy: 'CRITICAL'}];

return (
  <ClinicalResultView results={results} documents modified comments/>
);
```

## Questions:

**1) Should the time display be part of the ClinicalResultView or part of a larger reusable component?**
There is one use case where the time is not shown on the ClinicalResultView. In our Detail View for a measurement, the ClinicalResultView is shown in one LabelValueView and the result time is shown in separate LabelValueView. Additionally we also break up the results for blood pressure such that the systolic and diastolic values are shown in separate LabelValueView. This makes me wonder if the ClinicalResultView really should be a composite view build up of one or more ResultViews that can be used on their own. I'm not confident enough of our usage in the Detail View enough to say this should happen. I tend to believe that the time display should be a first class attribute of the ClinicalResultView and not an attribute provided by another wrapping element.

**2) Should concept display be part of the ClinicalResultView or part of a larger reusable component?**
Currently we show a concept display in some circumstances where a list of result cards are shown with different concepts. This is a minority use case, but when it occured the concept display (Blood Pressure Invasive) would show under the time display. I'm not convinced that the concept display should be supported as a first class prop on the ClinicalResultView, and tend to believe it should be an attribute on a card that contains the ClinicalResultView. My preference would to leave this out of the API for now and potentially add it later if we have a compelling enough argument.

**3) Should it be a selectable element by itself, or part of a larger selectable item?**
Right now the API we have internally has this result as selectable, but I believe the ClinicalResultView should not be intrinsically selectable. In the future I see this reusable component having a larger wrapper view like a ClinicalResultCard

**4) Is it ok to have truncation default to true?** 
In the majority of our use cases, truncation was necessary as the view was embedded in a grid or list layout that necessitated a fix width and height. There definitely was a need to have truncation disabled when navigation was terminated, but this wasn't the majority of use cases. My thought is we keep truncation as false as the default and assume nothing around the majority of use cases for this view.

**5) Should normalcy for a given result value be a limited enum set, or be an icon and rgb color?**
Currently our internal implementation is restricted to several icons around the normalcy, such as Critical, High, Low. The FHIR specification has a much [larger set](https://www.hl7.org/fhir/valueset-observation-interpretation.html).  While I think it's convienent for consumers to pass a normalcy string, I'd like to see this to be flexible to accomidate other workflows. I'm not sure how we should go about this..perhaps we expose a helper function to provide the correct icon/colors, or allow an override for the icon/color.  

**6) Should this be called ClincalResultView, or something else?**

**Comment by DHoude** [comment]
@jeffmerten  I think we should meet for a few minutes to discuss these questions.  Maybe include Doug, as he wrote a lot of this code to start with.   I am not comfortable with changing much here.  I can see your point with #5 in an open source component.  
For #7 I can't think of any other separator in labs or vitals; also, there are 2 components, the one with the separator is specifically for Blood Pressures.

**Comment by rakshith91** [comment]
Allowing a custom icon and color is necessary since it seems that [FHIR](https://www.hl7.org/fhir/observation.html) has a huge set of icons. 
We would have 
```
const variants = {
  LOW: 'low',
  HIGH: 'high',
  CRITICAL: 'critical',
  CUSTOM: 'custom',
};
```
and then we have a prop 
```
  /**
   * Variants for icon. Allows low, high critical and custom
   */
  variant: PropTypes.oneOf(Object.values(variants)),
```
which defaults to 
`  variant: variants.CUSTOM,`
We allow passing an icon and color in results but they would have default values themeable in css if the variant is low, high or critical.

**Comment by neilpfeiffer** [comment]
Closing old issue and replacing with new issue #576 with updated details.
