### ISSUE TITLE
Uplift to React 16.2.0

### ISSUE THREAD

**Issue by benbcai** [cerner/terra-clinical#269]
# Issue Description
Uplift to React 16.2.0

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Depends on React 16.2.0

## Current Behavior
Depends on React 15.5.4

**Comment by emilyrohrbough** [comment]
https://github.com/cerner/terra-clinical/issues/161

**Comment by benbcai** [comment]
Closing as a duplicate.
