### ISSUE TITLE
Remove Test Routes & Test Links

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#275]
# Issue Description
Once uplifted to terra-site v2.0.0, the site navigation will be auto-generated by terra-site. The removes the need to create the TestRoutes and TestLink files.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by emilyrohrbough** [comment]
Blocked by:
- [ ] https://github.com/cerner/terra-clinical/issues/274

**Comment by alecrowen** [comment]
Done

**Comment by emilyrohrbough** [comment]
There are several components that need this change still. For example: https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-no-data-view/tests/nightwatch/NoDataViewTestRoutes.jsx

**Comment by mjhenkes** [comment]
i got ahead of myself here.

**Comment by emilyrohrbough** [comment]
Only a few left before this is done!
