### ISSUE TITLE
Migrate Components to Use New File Structure

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#277]
# Issue Description
With the deprecation of terra-clinical-site, all page and test examples should live together. The new file structure decided is as follows:
```
component
    /docs
    /examples
        /test-examples  # what use to be in the nightwatch dir
        Index.site-page.js
    /src
    /tests
```

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
This update can roll out in increments. Once each package is updated to contain their own files, terra-clinical-site can be removed.

### Packages to be uplifted:
- [ ] action-header
- [ ] detail-view
- [ ] header
- [ ] item-collection
- [ ] item-display
- [ ] item-view
- [ ] label-value-view

**Comment by Blackop778** [comment]
This was handled in #336
