### ISSUE TITLE
Add webdriver.io tests for terra-clinical-detail-view

### ISSUE THREAD

**Issue by rakshith91** [cerner/terra-clinical#282]
# Issue Description
Consume wdio tests in terra-clinical-detail-view and remove the existing nightwatch tests.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

**Comment by alecrowen** [comment]
Done and merged

**Comment by rakshith91** [comment]
Reopening this. There are no wdio tests for `terra-clinical-detail-view`
