### ISSUE TITLE
Add lib to gitignore

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#31]
### Description of Issue
A common pattern for npm modules is to add the lib(es5) directory to the .gitignore and add the src(es6) directory to the .npmignore. [Babel is an example of this pattern](https://github.com/babel/babel/tree/7.0/packages/babel-core) that also uses lerna. 

More information can be found in this article:
http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/

To Do:
- [x] Update the .gitignore to no longer check in the lib directory.
- [x] We can probably remove the prepush script after this is completed.
- [x] Compile for travis CI tests
- [x] Add script which compiles before publishing https://github.com/cerner/terra-core/issues/353

Reference: https://github.com/cerner/terra-core/issues/316

**Comment by emilyrohrbough** [comment]
https://github.com/cerner/terra-core/issues/78

**Comment by emilyrohrbough** [comment]
This [branch](https://github.com/cerner/terra-clinical/tree/terra-core-%23316-sync) addresses tasks 1-3.

Task 4 is blocked on this issue: https://github.com/cerner/terra-clinical/issues/54.

**Comment by emilyrohrbough** [comment]
Task 4 is blocked on this issue: https://github.com/cerner/terra-clinical/issues/54.

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-core/pull/414

**Comment by emilyrohrbough** [comment]
Issue #54 has been resolved with PR #75. Task 4 is complete.
