### ISSUE TITLE
Alias moment and react-dom

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#32]
- Alias moment and react-dom.  There were multiple copies of moment being pulled into our bundle. This is due to react-datepicker having moment as a dependency instead of a peerDependency. React-datepicker has an outstanding issue for this here: https://github.com/Hacker0x01/react-datepicker/issues/122

After adding the alias for moment and react-dom, we can see that only one copy is pulled into our bundle. 

References: https://github.com/cerner/terra-core/pull/297

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-core/blob/master/packages/terra-site/webpack.config.js#L81-L86
^ To resolve this issue, update the terra-clinical-site webpack config to match what we have above.
