### ISSUE TITLE
Create DataGrid

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-clinical#325]
# Issue Description
As more complex table structures are investigated, a couple necessary features have become apparent:
* Fixed column headers that are visible at all times
* Optional fixed-positioned columns that do not respond to horizontal overflow
* Resizable column widths
* Subsections w/ collapsible behavior
* Both per-row and per-cell selections

The majority of these features would be hard (or impossible) to implement within the existing Table component. We are therefore going to create a new structure called a DataGrid to provide this functionality.

Tech design to follow.

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
@ryanthemanuel @tbiethman Resolved by https://github.com/cerner/terra-clinical/pull/387?

**Comment by tbiethman** [comment]
@emilyrohrbough I'm sure as heck not going to make another one :D
