### ISSUE TITLE
Fallback text for icons in ActionHeader buttons

### ISSUE THREAD

**Issue by jmsv6d** [cerner/terra-clinical#37]
### Description of Issue
The icons used in the action header buttons need to have fallback text in case the icons fail to load.

**Comment by Matt-Butler** [comment]
@jmsv6d What are the cases where the icons fail to load?

**Comment by jmsv6d** [comment]
@Matt-Butler This was a change that was made recently in our legacy component. Looking back at the issue, it was with font icons failing to load. I'm not sure if this could still happen with svg icons.

**Comment by ryanthemanuel** [comment]
Closed with #50
