### ISSUE TITLE
[Label Value View] Allow span elements as label and value to support FormattedMessage

### ISSUE THREAD

**Issue by ghost** [cerner/terra-clinical#371]
**Issue:** Support Span Elements as label and value in label value component

**Concerns:**
Today the component defines its props label and value as strings. When a consumer is using Formatted Message(react-intl) to get translated strings from the locale files the resulting label would be a span element.

**Impact:**
Not a bug or blocker.
The component does load fine with a browser warning
_Failed prop type: Invalid prop `label` of type `object` supplied to `LabelValueView`, expected `string`_

**Suggestion:**
It would be nice to not have this component throw the warning and allow span elements.

**Comment by emilyrohrbough** [comment]
I am curious as to how you are formatting your messages using `react-intl`. When looking at [their doc](https://github.com/yahoo/react-intl/wiki/API#formatmessage), they indicate a translated message is returned as a string and when we use in terra-alert to supply a string to terra-button's text prop, the message is returned without a span https://github.com/cerner/terra-core/blob/master/packages/terra-alert/src/Alert.jsx#L156.

**Comment by vivekchittamuri** [comment]
We preferred to use the <FormattedMessage /> api from react-intl instead of using the intl.formatmessage api and thats how we end up with span elements.

**Comment by StephenEsser** [comment]
The label has UX driven CSS styles intended to be applied directly to a string. 

If FormattedMessage returns a non styled span element I would argue this is adding unnecessary additional markup into the dom. 

Opening the API to accept a node type encourages the use of custom (non-themed) labels that deviate from the uniform approach within an application. 

Until there is a use case for custom content / styled labels I think the `string` prop-type remains the most appropriate.

**Comment by vivekchittamuri** [comment]
Agreed. opening up the props to be custom content will defeat the UX driven uniform approach.

Our understanding so far around translations was that in the use-cases where there are multiple nested components, FormattedMessage turns out to be a handy way of getting the translations loaded without needing to wrap the component in injectIntl

I guess if we want to have the best of both worlds and use formatted message with label value view we might have to end up using something like this
```
<FormattedMessage id="title">
    {(txt) => (
        <LabelValueView label={txt} />
    )}
</FormattedMessage>
```
