### ISSUE TITLE
React 15.5 compatibility

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-clinical#39]
https://github.com/cerner/terra-core/issues/203

**Comment by emilyrohrbough** [comment]
6 of the 5 Jest tests are failing with the following warning:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead. 

The following packages from terra-core need released with the 15.5 update to remove the warning:
- [ ] terra-arrange
- [ ] terra-button
- [ ] terra-button-group
- [ ] terra-icon
- [ ] terra-responsive-element

**Comment by emilyrohrbough** [comment]
Running site results in the same warning within the console:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead. 

The follow packages from terra-core (not listed above) need to be released with the 15.5 update to remove the warning:
- [ ] terra-grid
- [ ] terra-list
- [ ] terra-markdown
- [ ] terra-props-table

**Comment by bjankord** [comment]
We'll want to get [this PR](https://github.com/cerner/terra-core/pull/348) landed before releasing all the terra-core components with compat for react 15.5. That PR should be ready pending the fix for heroku deployment lands soon.

**Comment by bjankord** [comment]
The following packages have been released with the react 15.5 compat code:

* terra-grid@2.3.0
* terra-list@0.2.0
* terra-markdown@0.4.0
* terra-props-table@0.4.0
