### ISSUE TITLE
Onset Picker crashing

### ISSUE THREAD

**Issue by PaulSolDev** [cerner/terra-clinical#396]
# Bug Report

## Description

Date field in Onset Picker is causing a crash when the value is cleared.

## Steps to Reproduce

1. Select 'Date' option in the onset picker
2. Clear the date field 
3. Browser page appears to crash/ go blank

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/29487301/45773977-692fb400-bc11-11e8-8b38-e5cf47c3776c.png)

## Expected Behavior

Expect date value to clear and for the empty field to support entry of a new date value.

## Environment

* Component Name and Version: Onset Picker
* Browser Name and Version: All browsers
* Node/npm Version: [e.g. Node 8/npm 5]
* Operating System and version (desktop or mobile): Tested on Desktop

**Comment by ryanthemanuel** [comment]
@doogthemushroom is going to pick this up.

**Comment by emilyrohrbough** [comment]
Resolved in https://github.com/cerner/terra-clinical/pull/427
