### ISSUE TITLE
terra-clinical-item-collection not resizing correctly

### ISSUE THREAD

**Issue by chiefscott34** [cerner/terra-clinical#399]
# Feature Request

## Description
My solution has wired that when an Item within the Item Collection is selected, a ResponsiveElement
is displayed.  I propose that once the ResponsiveElement is displayed, the selected Item within the collection is moved to be visible in all form factor view.

## Additional Context / Screenshots

If I select the last order in this scrollable view, 
![terrascreenshot2](https://user-images.githubusercontent.com/43452251/45964928-aff42400-bfec-11e8-9af0-fa20ee100978.png)

the slide panel opens and the view changes to list view, so the order gets pushed off to the bottom
![terrascreenshot3](https://user-images.githubusercontent.com/43452251/45964929-aff42400-bfec-11e8-8eaf-3157970831e0.png)

but if we scroll down, the order is still selected.
![terrascreenshot1](https://user-images.githubusercontent.com/43452251/45964930-aff42400-bfec-11e8-8605-1d49b2b3e57a.png)

**Comment by bjankord** [comment]
https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate may offer some insight to scroll position behavior.
