### ISSUE TITLE
Update the doc site for terra-clinical-item-view to be more realistic

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-clinical#41]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
Since we are using the doc site to demo components right now, I'd like to update the doc site to be more realistic for terra-clinical-item-view.  It's possible we might want to engage some functional people on this to get more realistic data.

**Comment by emilyrohrbough** [comment]
Resolved in #108.
