### ISSUE TITLE
[terra-clinical-item-collection] Display chevron in table format.

### ISSUE THREAD

**Issue by jmsv6d** [cerner/terra-clinical#411]
# Feature Request
Option to display chevron in the table format as well as the list format.

## Description
The particular scenario this is being requested for: The component is displayed in "table" format without chevrons, user selects a row in the table to disclose a slide panel. The item collection's space shrinks and is update to display in "list" format which has chevrons. Consumers would like to consistently use the chevron as a disclosure indicator in both formats.

**Comment by PayalSawant** [comment]
I would like to do this.

**Comment by PayalSawant** [comment]
@bjankord  I would like to work on this

**Comment by nramamurth** [comment]
@bjankord 
Has this issue been approved to be worked upon?

@neilpfeiffer 
I vaguely remember hearing that the Table intentionally moved away from showing the chevron in a row (which I think it did in TRVM implementation. I could be wrong here.). Is this an exception for Clinical Item Collection Table View? I however played around to see if I see could put the `chevron` as part of `endAccessory` in the Table View (with Selectable content) and here's what it looks like - 

<img width="958" alt="Screen Shot 2019-07-18 at 12 22 13 PM" src="https://user-images.githubusercontent.com/10090859/61435879-2df83180-a957-11e9-9f35-45decd517fd6.png">

What are your thoughts?
