### ISSUE TITLE
Decouple Functional and Custom Property WebDriver Tests

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-clinical#423]
## Issue
WebDriver tests contain both functional test steps and custom property theme tests within the same spec file. When tests are shared across libraries, specifically theming libraries, it is not possible to skip tests that are applying a mock theme. This introduces a risk of generating unnecessary and inaccurate screenshots.

Tests that contain both functional steps and custom property alteration steps generate a screenshot that includes a mock theme and inaccurately represents the component during that step.

## Proposal
Decouple functional and custom property WebDriver tests by separating them into different files and moving the custom property tests into a unique directory. This enables explicit control over which set of tests consumers want to run and makes each spec file's intention more clear.

Functional Tests: 
```
/wdio/test-name.spec
```

WDIO Tests:
```
        ↓ Directory
/wdio/theme/test-name.spec
```

## Component Checklist
- [ ] terra-clinical-application
- [ ] terra-clinical-data-grid
- [ ] terra-clinical-detail-view
- [ ] terra-clinical-header
- [ ] terra-clinical-item-collection
- [ ] terra-clinical-item-display
- [ ] terra-clinical-item-view
- [ ] terra-clinical-label-value-view
- [ ] terra-clinical-onset-picker

**Comment by StephenEsser** [comment]
Hey @gabeparra01

Thanks for looking into this one. I think we found a workaround for this issue that resolves the majority of the issues noted in the summary. I'm going to go ahead and close this issue.

**Comment by gabeparra01** [comment]
@StephenEsser ok thanks for letting me know
