### ISSUE TITLE
Update Dependency Version

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#441]
# Feature Request

## Description
Sync with https://github.com/cerner/terra-framework/pull/400

This should slim our entry point size and remove console warning for 'mismatching' dependency versions specified in the project even though the latest version is being pulled in.

All terra-core components should be updated to be the latest major version. i.e. `v1.0.0` or `v2.0.0` etc.

**Comment by ryanthemanuel** [comment]
This was done as part of the theme major version bumps in core and clinical.  Closing
