### ISSUE TITLE
Perform Audit for Vulnerabilities 

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#442]
# Feature Request

## Description
Perform Audit for Vulnerabilities. When running npm install I am seeing:

![screen shot 2019-01-03 at 4 08 32 pm](https://user-images.githubusercontent.com/14099737/50665554-b8a6af80-0f76-11e9-90b2-cf6b8854b51c.png)

## Mentions
@mjhenkes @ryanthemanuel @dkasper-was-taken @tbiethman @benbcai

**Comment by gabeparra01** [comment]
@emilyrohrbough are there any other steps necessary to reproduce that console output? I just ran npm install and I do not see a vulnerabilities message. Maybe it got resolved?

**Comment by bjankord** [comment]
I believe you need npm v6 to run the audit command.

**Comment by gabeparra01** [comment]
@bjankord Yeah that was my issue. I am seeing the audit message now
