### ISSUE TITLE
Clinical Severity Represented in Clinical Detail View

### ISSUE THREAD

**Issue by ChelseaRyanAnderson** [cerner/terra-clinical#449]
# Feature Request

## Description
Within the card of a component such as allergies, problems, labs, etc. we could have values that are clinically severe and display with bold, red text. It would be great if we could carry that text treatment into the detail panel as well since mobile users won't be able to view the card, which gives context to the detail panel. 

## Additional Context / Screenshots
Current state:
![image](https://user-images.githubusercontent.com/35141408/50778946-bc7f4e00-1264-11e9-9bbf-3b35aa313852.png)

Proposed state:
![image](https://user-images.githubusercontent.com/35141408/50779109-1f70e500-1265-11e9-837c-0ce0743fca5d.png)

## @ Mentions
I spoke with @neilpfeiffer about this earlier and he noted that this is functionality the team was planning on updating at some point.

**Comment by nramamurth** [comment]
@ChelseaRyanAnderson @neilpfeiffer 

I am trying to understand the requirement better - so let's say that the consumers create a `DetailView` similar to what is being shown below. 

<img width="947" alt="Screen Shot 2019-04-22 at 11 05 16 AM" src="https://user-images.githubusercontent.com/10090859/56484733-ad0fd200-64ee-11e9-9910-249c35211215.png">

In my understanding, the consumers can have their [Clinical Label Value View](https://engineering.cerner.com/terra-ui/#/components/terra-clinical-label-value-view/clinical-label-value-view/clinical-label-value-view) created with a 'Text Input' or 'Node Input'. It looks like _Allergies_ creates its Clinical Label Value View with 'Text Input'. Wouldn't this issue be solved if 'Severity' is created with a 'Node Input' instead, let's say - a 'Terra Clinical Item Display' element similar to what is being shown below? 

<img width="822" alt="Screen Shot 2019-04-22 at 11 02 01 AM" src="https://user-images.githubusercontent.com/10090859/56484912-74242d00-64ef-11e9-95d1-6c047d9f25dc.png">

**Comment by nramamurth** [comment]
With respect to the colour of the `title` of Detail View, do we want that to be one of the variants allowed by Clinical Item Display (i.e., `secondary`, `attention`, `strikeThrough`, or `strong`) or could it be **anything** as per consumers' wish?

- If the consumers can style it however the way they want, then I'd propose adding a new `prop` called `titleAttributes` (or something similar) via which they can pass down a custom class that could be used to style.

- If the consumers should be restricted to use one of those four visual styles mentioned above, then we could do something similar to what [ItemDisplay](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-item-display/src/ItemDisplay.jsx#L25) does. 

Also, will there be a need in the future to accommodate similar changes to `secondaryTitles` and `subtitles` as well?

**Comment by ShettyAkarsh** [comment]
@ChelseaRyanAnderson  Do we need to Highlight the severity and title values only for the cards selected for Allergies, problems, labs ? or else should that be similar for all of them ?

**Comment by ChelseaRyanAnderson** [comment]
@ShettyAkarsh sorry for the delayed response! I'm interpreting this as "Should we treat clinical cards/details different or have all cards with strong text for title and value the same way?" and I honestly don't know what makes more sense from a development perspective. @neilpfeiffer thoughts?

**Comment by nramamurth** [comment]
Update from offline discussion with Neil:

> For the title, we’ll need it to be node for the clinical result component we’ll be making for labs/vitals results (has multiple elements: high/low/critical icons, values with colors, units of measure as secondary, etc.). That will be much easier than to overload the title with additional props similar to ItemDisplay. I’ll need to work out the prop details, it may be that we instead add a custom title that replaces title if valued, one has defined markup/style, the other doesn’t perhaps. Or something else, not sure yet.

**Comment by neilpfeiffer** [comment]
Updates In Progress.
