### ISSUE TITLE
Provide attribute on DataGrid section header

### ISSUE THREAD

**Issue by jeffmerten** [cerner/terra-clinical#457]
# Feature Request

## Description
Provide an attribute on the section header of data grid.

## Additional Context / Screenshots
Our current solution has a navigation workflow where the user taps on a cell that effectively represents that section of the DataGrid. We'd like to add an attribute to the section header so we can scroll to that section on component mount.

## @ Mentions
@tbiethman

**Comment by tbiethman** [comment]
Fixed by #458
