### ISSUE TITLE
Replace local keyCode value definitions with keycode-js dependency

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-clinical#467]
# Feature Request

## Description
terra-core packages that parse keyboard input typically define constants for the various keyCode values they care about. There's a lot of duplication between packages, and we've talked about drying up those definitions for a while. 

We could replace those local keyCode definitions with values from [keycode-js](https://www.npmjs.com/package/keycode-js), a small and well-supported third-party package.

**Comment by yuderekyu** [comment]
@anjaliroy19 assigning you this so we can stake our claim 🔪

**Comment by PayalSawant** [comment]
I would be willing to work on this if thats ok @yuderekyu

**Comment by emilyrohrbough** [comment]
@PayalSawant There is already a code review out for this change. Looks like the issue wasn't referenced: https://github.com/cerner/terra-clinical/pull/479
