### ISSUE TITLE
terra-clinical-header applying additional 2px margin on end button in safari

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-clinical#471]
# Bug Report

## Description
This only occurs in the safari browser.  When using the terra-clinical-header and or even the terra-clinical-action-header, when have a close button in the endContent area and a button or collapsible-menu-view as a child component of the header, the components are no longer vertically aligned.  Can be reproduced today on terra-ui site using the terra-clinical-action-header's example with the collapsible-menu-view.

## Steps to Reproduce
1.  Use a clinical-header or clinical-action-header
2.  Pass a button into the endContent prop or use the onClose prop
3.  Add a child component of a button or collapsible-menu-view
4.  Use the safari browser
5.  Notice the tops of the components are not vertically aligned by 2px

## Additional Context / Screenshots
inspector showing that the alignment is off
<img width="422" alt="Screen Shot 2019-03-14 at 12 35 56 PM" src="https://user-images.githubusercontent.com/1711642/54379105-bdfb3700-4656-11e9-916f-bcf181f3949e.png">

inspector that shows is happening for the button tag applying the margin
<img width="785" alt="Screen Shot 2019-03-14 at 12 34 47 PM" src="https://user-images.githubusercontent.com/1711642/54379066-ad4ac100-4656-11e9-9413-93472527ae67.png">

## Expected Behavior
The tops of the components should be horizontally aligned

## Environment
Occurs in the safari browser.  Not seen in chrome or firefox browsers.

**Comment by neilpfeiffer** [comment]
@nramamurth Adding a reset of `margin:0;` on the base button class should resolve this.

Thanks @kschuste for finding.

**Comment by nramamurth** [comment]
It seems like Safari adds `2px` margin by default to a `Button` and resetting it in [Button.module.scss](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/Button.module.scss#L26) should resolve it. 

**References:** 
1. https://css-tricks.com/overriding-default-button-styles/#article-header-id-2
2. https://github.com/google/material-design-lite/issues/4008

**Comment by nramamurth** [comment]
@neilpfeiffer Bingo! 🎉
