### ISSUE TITLE
terra-clinical-header and collapsible-menu-view overlapping on IE

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-clinical#478]
# Bug Report
Only when running in IE do we see this issue of the collapsible-menu-view buttons overlapping our end-content button.

## Description
When the collapsible-menu-view is rendered as a child of the terra-clinical-header, along with an additional button as a child component, the collapsible-menu-view's buttons can overlap the latter child component button.  This only occurs in IE and not in the other browsers.

## Steps to Reproduce
```javascript
<ActionHeader>
        <Fragment>
          <CollapsibleMenuView menuWidth={`${CollapsibleMenuViewItem.Opts.widths[160]}`}>
        {
          availableActions.map(availableAction => (
            <CollapsibleMenuView.Item
              text="Action Text"
              key="Action Text"
              onClick={this.handleActionClick}
              isDisabled=false
            />
          ))
        }
      </CollapsibleMenuView>
          <Spacer paddingLeft="small">
            <Button
              text="Done"
              onClick={this.onClick}
              className="done-button"
            />
          </Spacer>
        </Fragment>
      </ActionHeader>
```

## Additional Context / Screenshots
![MicrosoftTeams-imagea5f2c5bb485b5936bc034cb06bcdd9ecdbe9b23505f4ddff09ccac1dc59a68a3](https://user-images.githubusercontent.com/1711642/55361256-50e00200-549c-11e9-8733-9af795db2de9.png)
![MicrosoftTeams-imageecd1662d0c1ea283b89f9ab78c5231b97d6feffa7484adc7b66ddb45f8ec91c3](https://user-images.githubusercontent.com/1711642/55361262-563d4c80-549c-11e9-95fe-9a546696538d.png)

## Expected Behavior
The collapsible-menu-view will collapse its buttons into the menu button and not overlap the other child element.

**Comment by nramamurth** [comment]
@kschuste I was not able to reproduce this issue - could you tell me what I am missing? I did not see the issue on both `terra-clinical-header` and `terra-action-header` on the lines of the example that is provided. 

> Only when running in IE do we see this issue of the collapsible-menu-view buttons overlapping our end-content button.

How are you passing the `end-content`?

**Clinical Header with end-content on IE 11:**

![Screen Shot 2019-04-02 at 4 26 26 PM](https://user-images.githubusercontent.com/10090859/55397621-40935a00-5564-11e9-8dbc-74427457d78b.png)

**Clinical Header without end-content on IE 11:** 

![Screen Shot 2019-04-02 at 4 31 55 PM](https://user-images.githubusercontent.com/10090859/55397891-e9da5000-5564-11e9-9fd4-110cd74e873c.png)

**Example:** 

```
    <Header 
       id="Header" 
       endContent={<div><Button text="End Content" style={{ margin: '0 10px 0 10px' }} /></div>}
    >
        <React.Fragment>
            <CollapsibleMenuView>
                <CollapsibleMenuView.Item text="Collapsible Menu" key="button" />
            </CollapsibleMenuView>
            <Spacer paddingLeft="small">
                <Button text="Child" onClick={() => { }} />
            </Spacer>
        </React.Fragment>
    </Header>
```

**Comment by ShettyAkarsh** [comment]
@nramamurth , i am able to reproduce this issue with your above code sample. when i try to resize the window in IE Browser.

![image](https://user-images.githubusercontent.com/45097016/55465379-a5a98700-561a-11e9-8bfb-76cc96a4939c.png)

**Comment by nramamurth** [comment]
OH! Thanks for the heads-up, I shall dig further.

**Comment by jmsv6d** [comment]
This is not an expected use case of the clinical header. The header api only allows for 1 child element to be passed in and the collapsible menu view cannot account for sibling components in it's collapsing logic. I would say you should either have the last button be within the same collapsible menu view or put it in the endContent prop.

**Comment by nramamurth** [comment]
> The header api only allows for 1 child element to be passed in..

@jmsv6d @bjankord @neilpfeiffer I am curious, is the following snippet not a valid use-case for Clinical Header? Is it the onus of the `terra-clinical-header` or the consumer to account for CSS issues in this case?

```
<Header>
   <div className="some-wrapper">
      <Component />
      <Component />
   </div>
</Header>
```

Also, I was able to confirm that @jmsv6d's suggestion to have the 'other child component' as part of the `endContent` seems to work fine.

**Comment by jmsv6d** [comment]
The use of the children in clinical header was designed explicitly for the use of collapsible menu view. Styles are decorated onto the child component in order to make the collapsible menu view work as expected in the header space, restricting the area that the collapsible menu can take up and allowing that bucket to resize appropriately. The collapsible menu logic is designed to fill it's entire parent container. It can't be expected to work correctly with a sibling component. That would require the collapsible menu to not be self contained and to be aware of what was around it. There needs to be a container component that lays out the collapsible menu next to the other element. The header will do this if you put the collapsible menu alone as the only child and then any additional elements in the endContent bucket.

**Comment by jmsv6d** [comment]
The header does not provide a layout within any of the buckets it provides. If the consumer needs to display more than one element within a bucket it is up to the consumer to create a component that would style/layout those components within that bucket.

**Comment by nramamurth** [comment]
Should this be officially documented?
