### ISSUE TITLE
Collapsible menu view not working as expected in IE10

### ISSUE THREAD

**Issue by parvezalisha** [cerner/terra-clinical#483]
# Bug Report

## Description
collapsible-menu-view overlaps in IE 10. I am using collapsible menu view inside terra-clinical-header as an only child. Done button is part of endContent prop of the header. It works fine in firefox and chrome but not in IE 10

## Steps to Reproduce
Below code should reproduce it:
```
      <Header
        endContent={(
          <Spacer paddingLeft="small">
            <Button
              text="Done"
              className="done-button"
            />
          </Spacer>
        )}
      >
        <CollapsibleMenuView className="available-actions-menu" menuWidth={`${CollapsibleMenuViewItem.Opts.widths[160]}`}>
          <CollapsibleMenuView.Item
            name="collapsible-menu-item"
            className="collapsible-menu-item"
            text="A Collapsed Button"
            key="collapsible-menu-item"
            onClick={this.handleClick}
          />
        </CollapsibleMenuView>
      </Header>
```

## Additional Context / Screenshots

![Screen Shot 2019-04-09 at 1 54 55 PM](https://user-images.githubusercontent.com/10690028/55827261-5ad2b800-5acf-11e9-82ab-25c54540f768.png)

## Environment

* Component Name and Version: terra-collapsible-menu-view: "3.33.0"
* Browser Name and Version: IE 10
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version: webpack 4.29.6
* Operating System and version (desktop or mobile): VirtualBox VM with Windows 7 (32 bit)

**Comment by ryanthemanuel** [comment]
@nramamurth I moved this.
