### ISSUE TITLE
Update terra-dev-site to v4

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-clinical#486]
# Feature Request

## Description
terra-dev-site v4 is available. We should [update our dependency on terra-dev-site](https://github.com/cerner/terra-clinical/blob/master/package.json#L90) to `^4.0.0`.

**Comment by PayalSawant** [comment]
I would be willing to work on this if thats ok @bjankord

**Comment by bjankord** [comment]
Sure thing, that would be very helpful.
