### ISSUE TITLE
Remove dependency on terra-app-delegate in terra-clinical-application

### ISSUE THREAD

**Issue by andrewnottaviano** [cerner/terra-clinical#487]
# Feature Request

## Description

We are using terra-app-delegate in terra-clinical-application, and it needs to be removed since it is deprecated. [Here](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-application/package.json#L30) is where we are pulling it in.

**Comment by emilyrohrbough** [comment]
terra-clinical-application was deprecated in https://github.com/cerner/terra-clinical/issues/488 on July 16, 2019. This change is no longer needed.
