### ISSUE TITLE
Update Title of Terra Clinical Detail View to accept a react component

### ISSUE THREAD

**Issue by vaibhavmsv** [cerner/terra-clinical#492]
# Feature Request

## Description
Currently Terra-Clinical-Detail-View has a prop called title which accepts string. It would be great if this can be updated to accept a react component.
We have an ComponentA which returns terra-clinical-item-view component which has terra-avatar as startAccessory. That component should be kept as an Title to Terra-Clinical-Detail-View component.
Once i had that component inside Terra-Clinical-Detail-View as title, the image looks like this 
![image](https://user-images.githubusercontent.com/18640970/56731166-6e407d00-6777-11e9-9db9-3654fda5a21c.png)
Here you can see the terra-avatar component became elliptical where it should be circular.
But i did tried to remove the ComponentA(which returns terra-clinical-item-view component which has terra-avatar as startAccessory) out of title prop in Terra-Clinical-Detail-View, but there is a spacing issue that gets created from Terra-Clinical-Detail-View. Below is the image for that. 
![image](https://user-images.githubusercontent.com/18640970/56733453-d72af380-677d-11e9-828d-147ff954e772.png)
Once i kept title as empty and there is a lot of spacing between my ComponentA and Terra-Clinical-Detail-View. 
![image](https://user-images.githubusercontent.com/18640970/56733535-09d4ec00-677e-11e9-8f9a-b74f0404ebb2.png)

**Comment by neilpfeiffer** [comment]
Potentially duplicate of https://github.com/cerner/terra-clinical/issues/449

**Comment by neilpfeiffer** [comment]
TODO: Update description of issue above with new approach to split off complex detail-view header layouts as their own components (explore having concept teams manage and control these highly specific components), detailed here in request for adjusting details needed for Multiple-Ingredient Medication Headers: https://github.com/cerner/terra-clinical/issues/611#issuecomment-590917093

Related issues for Clinical Result header: https://github.com/cerner/terra-clinical/issues/449 and https://github.com/cerner/terra-clinical/issues/509
