### ISSUE TITLE
[terra-clinical-header] is not aligning contents at center. 

### ISSUE THREAD

**Issue by navya-devp** [cerner/terra-clinical#538]
# Bug Report

## Description

A change in here https://github.com/cerner/terra-clinical/commit/d82c1153761e0209fd878cc6e2df0add9dbe44dd#diff-cb6f9577990c03c3f6150e592178e615R35 is aligning starting content in header to align at top but not at center. 

It is supposed to be aligned at center.
Reverting align-self: center to align-items: center might work.

**Comment by lokesh-0813** [comment]
@navya-devp  Can you provide steps to reproduce this issue ? 
Or Can you share some Screenshots ? And which version of terra-clinical-header you are using and which browser. Thank you.

**Comment by vb057454** [comment]
### We had the similar issue, version we use is ^3.2.0
<img width="1680" alt="Screen Shot 2019-07-31 at 4 57 57 PM" src="https://user-images.githubusercontent.com/46331155/62251156-76cad400-b3b4-11e9-8988-3799c23cf7cb.png">

**Comment by ryanthemanuel** [comment]
Closed with #550
