### ISSUE TITLE
Add script for lerna publish

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-clinical#54]
We are starting to use [lerna publish](https://github.com/lerna/lerna#publish) to release several packages at once. We would like to add a script that uses lerna-publish.

- [x] add script to compile, test, and lerna publish. Similar to what [cloudflare-ui does](https://github.com/cloudflare/cf-ui/blob/master/package.json#L24)
- [x] remove existing release script: https://github.com/cerner/terra-core/tree/master/scripts/release

https://github.com/cerner/terra-core/issues/369

**Comment by emilyrohrbough** [comment]
Resolved in #75
