### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-clinical#549]
# Bug Report

## Description

We're seeing "ResizeObserver loop limit exceeded" on https://engineering.cerner.com/terra-ui/components/terra-clinical-data-grid/clinical-data-grid/datagrid-examples/datagrid-with-selections

## Additional Context / Screenshots

https://rpm.newrelic.com/accounts/1721539/browser/142381315/errors/details#?tw_start=&tw_end=now&tw_offset=604800000&selectedItem=ResizeObserver%20loop%20limit%20exceeded&selectedTab=instances

## Environment

* Component Name and Version: terra-clinical-data-grid
* Browser Name and Version: Chrome 75
* Operating System and version (desktop or mobile): Desktop Mac

**Comment by tbiethman** [comment]
Potentially related: https://github.com/cerner/terra-framework/pull/212
