### ISSUE TITLE
[terra-clinical-onset-picker] Switching to age granularity and back to any other granularity displays 1 year earlier.

### ISSUE THREAD

**Issue by po016255** [cerner/terra-clinical#558]
# Bug Report

## Description
In IE and Chrome if you load the onset datepicker with a month, year, or date granularity; choose age in the granularity drop down; and then go back to any other option, the date will display as the previous year.

## Steps to Reproduce
1. Populate control with an onsetDate prop date string formatted as YYYY-MM-DD, a granularity of year/month/date, and a birthdate formatted with full date/time but time zeroed out.  ex `birthdate={moment().subtract(150, 'years').startOf('day').format()}`, `1869-08-24T00:00:00-05:00` (also has the bad behavior passing UTC or YYYY-MM-DD),
2. Choose age in the granularity drop down.
3. Choose year, month or date in the granularity drop down.
4. The date will be displayed with the previous year using any granularity.

## Additional Context / Screenshots
(screens are taken in ie11)
Control initially populated:
![image](https://user-images.githubusercontent.com/12768193/63643802-b9738980-c69e-11e9-8f6d-b2e286737480.png)
Choosing age:
![image](https://user-images.githubusercontent.com/12768193/63643813-e3c54700-c69e-11e9-9bbe-94882202e7b1.png)
Choosing date:
![image](https://user-images.githubusercontent.com/12768193/63643818-0e170480-c69f-11e9-9c8e-83e24b80c914.png)
Choosing month:
![image](https://user-images.githubusercontent.com/12768193/63643822-2129d480-c69f-11e9-8597-2ad7ce6f44d1.png)
Choosing year:
![image](https://user-images.githubusercontent.com/12768193/63643825-356dd180-c69f-11e9-8c75-abc5abffd61b.png)

## Expected Behavior
The year should not show the previous year after choosing age.

## Possible Solution
This may be related to behavior in moment.js that treats YYYY formatted dates as UTC and converts them to local, while treating YYYY-MM and YYYY-MM-DD as local when doing `moment('dateString')` to initialize a date.  If any intermediate function treats the date as UTC and converts the passed in date object from UTC to local, it will subtract 6 hours and change the year because a year is represented in the underlying javascript Date object as YYYY-01-01T00:00:00.

## Environment

* Component Name and Version: [healthconcerns-js@1.1.1](https://github.cerner.com/ipoc/healthconcerns-js/blob/INTDEV-5012_AddComment_HCModify/src/health-concerns/components/details/HealthConcernModifyView.jsx#L866) 
* Browser Name and Version:
  * Chrome Version 76.0.3809.100 (Official Build) (64-bit)
  * IE11 Version 11.678.17763.0
* Node/npm Version: v8.11.3/5.6.0
* Webpack Version: 4.39.2 via terra-toolkit@4.29.0
* Operating System and version (desktop or mobile):
  * Front end - Windows 10 version 1809 (OS Build 17763.678)
  * Server - Ubuntu 16.04.6 LTS

**Comment by pranav300** [comment]
@po016255 I tried looking into this issue but was not able to reproduce it with steps provided by you, Could you check if you still face the issue with the latest version of `clinical-onset-picker`.

**Comment by nramamurth** [comment]
@po016255 Is this issue still legit with the latest version?
