### ISSUE TITLE
[terra-clinical-onset-picker] Make birthdate optional

### ISSUE THREAD

**Issue by po016255** [cerner/terra-clinical#559]
# Feature Request

## Description
Currently birthdate is required, this means we cannot hide the age option.  If our component is being built out incrementally this can mean releasing code before having the birthdate information for the patient. We have to then choose a value such as 150 years ago for birthdate.  It is not ideal to have an age option visible to the user that isn't correct.  Odds are users would see it as a bug.

If birthdate was optional, the age option could be automatically removed from the granularity drop down and the user would not have the ability to see it or choose it.

To handle the minimum date functionality, a separate prop should be created called minDate that can be required or optional.  If optional just default to 150 years in the past.  If required, at least teams can set 150 years in the past if they don't want to restrict the user or they can set some other minimum that they do want.

**Comment by po016255** [comment]
Birthdate isn't always available when a patient checks in such as in an emergency situation, so it is possible for it to not be there.  That alone makes it odd that this control requires a birthdate.

**Comment by po016255** [comment]
This appears to be resolved with https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-onset-picker/CHANGELOG.md#fixed-1 the change to handle ages less than a week old.

When birthdate is not set, the age option is not given.

It may be worth updating the readmes to reflect this behavior since birthdate is no longer required.

**Comment by po016255** [comment]
When a blank date is passed in, we can choose any year or month via the date granularity.  
![image](https://user-images.githubusercontent.com/12768193/74491991-00467d00-4e93-11ea-9ed8-53805f62989f.png)

But when choosing month or year granularities, the year is restricted to the current year.
![image](https://user-images.githubusercontent.com/12768193/74492037-279d4a00-4e93-11ea-8653-a4b185ff6be3.png)

The month is also restricted to the current month.
![image](https://user-images.githubusercontent.com/12768193/74492094-4996cc80-4e93-11ea-8db9-287320937565.png)

**Comment by nramamurth** [comment]
@po016255 

Are you consuming the latest version of clinical-onset-picker? Also, could you confirm if you're noticing the above mentioned behaviour when the snippet looks similar to the one below ⬇️?

```
import React from 'react';
import OnsetPicker from 'terra-clinical-onset-picker';

export default () => (
  <OnsetPicker
    birthdate=""
    id="test"
    legend="Date of Onset"
  />
);
```

With the existing code, I'm afraid things will not work as expected if `birthDate` is blank or empty.
