### ISSUE TITLE
[clinical-data-grid] Ability to launch clinical data grid with specific scroll positioning 

### ISSUE THREAD

**Issue by habelk** [cerner/terra-clinical#580]
# Feature Request

## Description

This request is to expose a ref callback prop on the DataGrid to expose the overflow container. Most solutions seems to be displaying things chronologically. If that is the case I think we will want to show most recent data face up. Current default behavior does not support this. It will be nice if clinical data grid provides this flexibility of default scroll right vs scroll left. Only option we have now is to use CSS dependencies on internal class names.

Two other related requests 
1. Ability to hide scroll bar. In future we see a need to control horizontal scrolling using external controls.
2. Ability to detect Item visibility. Use case- when there are selections outside the view area in the data grid, we would like to notify the user that there are items selected outside the view area. 

## @ Mentions

@neilpfeiffer
@tbiethman 
@chaitu9916

**Comment by mjhenkes** [comment]
We will add a ref to the Datagrid. If you want to discuss the related requests, please log them separately.
