### ISSUE TITLE
[terra-clinical-onset-picker] age field not aligned properly in IE.

### ISSUE THREAD

**Issue by pranav300** [cerner/terra-clinical#586]
# Bug Report

## Description
The age field is getting misaligned in IE.

## Steps to Reproduce

1. Go to [clinical-onset-picker](https://engineering.cerner.com/terra-ui/components/terra-clinical-onset-picker/clinical-onset-picker/clinical-onset-picker)
2. Go to any of the examples. And change granularity to age

## Additional Context / Screenshots

![VirtualBox_Windows 7_08_11_2019_10_53_23](https://user-images.githubusercontent.com/29273628/68451778-1ac6e580-0216-11ea-88ad-89a9ad175eec.png)

## Expected Behavior

The age field must be aligned correctly in IE.

## Possible Solution

Add CSS property `display: flex;` to [this](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L495) div.

## Environment

* Component Name and Version: clinical-onset-picker v4.10.0
* Browser Name and Version: IE11
* Operating System and version (desktop): Windows 10

**Comment by neilpfeiffer** [comment]
Ready to work, UX to validate style adjustments in PR
