### ISSUE TITLE
[clinical-data-grid] Ability to disable default horizontal scrolling and its scrollbar.

### ISSUE THREAD

**Issue by chaitu9916** [cerner/terra-clinical#587]
# Feature Request

## Description

- Ability to hide scroll bar and restrict horizontal scroll by user only through set of button interactions as shown in attached image below.
   - Set the overflow-x for horizontal overflow container to hidden.
   - Remove/hide horizontal scrollbar.

## Additional Context / Screenshots
#580 -[clinical-data-grid] Ability to launch clinical data grid with specific scroll positioning
#585 - PR

![Navigation buttons](https://i.imgur.com/UYDA88V.png)

## @ Mentions
@habelk
@neilpfeiffer
@tbiethman
@mjhenkes 
@pranav300 
@nramamurth

**Comment by neilpfeiffer** [comment]
This is not a current design requirement that UX has for the `clinical-data-grid` (primarily designed for clinical worklists).

However - a new grid based component is needing to be created to better handle clinical results, so this request will be considered as part of the requirements needed to build a replacement `clinical-flow-grid` component.

Closing this issue and moving details as sub-item for #607
