### ISSUE TITLE
example in the wild?

### ISSUE THREAD

**Issue by cwiese** [cerner/terra-clinical#588]
We are a small Healthcare application development team looking at this framework potentially for our application front-end.   Is there any example application in the wild or that we can build.   Especially interested in the datagrid . Thanks

**Comment by mjhenkes** [comment]
Hey @cwiese, We (Cerner), don't have many examples of Terra being used in the wild. Most of our usages of it are internal. The closest example we have would be the [asvcd risk calculator](https://github.com/cerner/ascvd-risk-calculator) which is a bit out of date and still uses jquery. You can check out our documentation site [Terra-UI](https://engineering.cerner.com/terra-ui/getting-started/terra-ui/what-is-terra) for getting started and component documentation. Also check out our reusable [webpack config](https://github.com/cerner/terra-toolkit/blob/master/config/webpack/webpack.config.js) to help get started as terra can be pretty particular about how webpack is setup.

**Comment by mjhenkes** [comment]
If you have more questions on usage, feel free to log an issue and we'll try to help out.
