### ISSUE TITLE
[clinical-data-grid] Add option to include a delimiter between sections without headers

### ISSUE THREAD

**Issue by RHolland13** [cerner/terra-clinical#594]
# Feature Request

## Description

Currently sections which lack headers have no delineation between them.  This can cause the rows between adjacent sections to be difficult to distinguish, as well as making it difficult to tell where one section ends and another begins.
My team's suggestion is to allow us to enable a horizontal border between sections that can provide delineation between sections in this case.  We don't particularly care if this manifests as a border at the top of the section, or the bottom of the preceding section.  In fact, simply allowing us to specify a custom header for a section consisting only of this border would suffice.  Currently this does not work because the section header has a minimum height.

## Additional Context / Screenshots

Here is an example of what the grid looks like when it contains a bunch of sections with no headers which contain only one row each.
![image](https://user-images.githubusercontent.com/43245637/70448356-de311880-1a65-11ea-8b79-65d640905818.png)
Here is the same example with borders between the sections.
![image](https://user-images.githubusercontent.com/43245637/70453629-b6927e00-1a6e-11ea-857c-c18a8b49d0bb.png)
And a slightly less extreme example showing the borders between larger sections.
![image](https://user-images.githubusercontent.com/43245637/70453923-3587b680-1a6f-11ea-8cc6-fc01edc6d45c.png)

**Comment by neilpfeiffer** [comment]
This is not a current design requirement that UX has for the `clinical-data-grid` (primarily designed for clinical worklists).

However - a new grid based component is needing to be created to better handle clinical results, so this request will be considered as part of the requirements needed to build a replacement `clinical-flow-grid` component.

Closing this issue and moving details as sub-item for #607
