### ISSUE TITLE
[terra-clinical-result] Numeric value alignment

### ISSUE THREAD

**Issue by shinepd** [cerner/terra-clinical#617]
# Bug Report

## Description
Numeric values are misaligned in the Flowsheet Result Cell

## Steps to Reproduce
1. Create two Flowsheet Result Cells with numeric values with/without normalcy icons present.

## Additional Context / Screenshots

![numeric_alignment](https://user-images.githubusercontent.com/61854307/76432991-b1044700-6381-11ea-8eb6-34080b4f17ad.png)
![margin_highlight](https://user-images.githubusercontent.com/61854307/76432995-b2357400-6381-11ea-8fd7-4a32cd15cf60.png)

## Expected Behavior
All numeric values should be aligned on the left side of the cell, accounting for the normalcy icon.

## Environment

* Component Name and Version: terra-clinical-result@1.0.0
* Browser Name and Version: Chrome 80 / IE 11
* Node/npm Version: Node 8 / npm 6.13.4
* Webpack Version: ^4.41.5
* Operating System and version (desktop or mobile): desktop

**Comment by shinepd** [comment]
@mjhenkes as a consumer, we'd also like the ability to display a checkbox in the cell for selection of unverified values. This selection is independent of the pre-existing cell selection. As unverified values will not have a normalcy icon present, ideally there would be vertical alignment between the normalcy icon and checkbox. However, in order to accomplish this we'd need to know the width of the normalcy icon prior to rendering. If it makes more sense to set something up to chat about this, please let me know and I can schedule something.

**Comment by mjhenkes** [comment]
@shinepd Can you log a new issue for your request? (I'm assuming its a new request) We can discuss it there. This was closed because it was fixed (afaik) with PR #620.
