### ISSUE TITLE
[terra-clinical-result] Modified Icon pushed out of cell

### ISSUE THREAD

**Issue by shinepd** [cerner/terra-clinical#619]
# Bug Report

## Description
The modified icon is pushed out of the cell when "View Results" is present with the multiple result indicator. This icon can also be pushed out when a blood pressure cell contains a value with three digits for systolic/diastolic, both with normalcy icons and the multiple value ind.

## Steps to Reproduce

1. Create a modified Flowsheet Result Cell whose value exceeds the width of the cell to get "View Results" to display.
2. Add an additional result to get the multiple value ind to display.
3. May need to shrink browser window to reproduce the issue.

## Additional Context / Screenshots

![numeric_alignment](https://user-images.githubusercontent.com/61854307/76433776-ce85e080-6382-11ea-8bc5-1f4c714861fa.png)

## Expected Behavior
The modified icon should not be hidden beneath the cell next to it.

## Environment

* Component Name and Version: terra-clinical-result@1.0.0
* Browser Name and Version: IE 10 ** Updated to be IE 10 from IE 11 **
* Node/npm Version: Node 8 / npm 6.13.4
* Webpack Version: ^4.41.5
* Operating System and version (desktop or mobile): desktop

**Comment by PolymorphedSquirrel** [comment]
Additional context:  This needs to be consistent in IE10, IE11, and modern browsers.  IE10 screenshot is shown above.
