### ISSUE TITLE
[terra-clinical-result] Multiple Result Indicator shows interpretation coloration for in error results

### ISSUE THREAD

**Issue by PolymorphedSquirrel** [cerner/terra-clinical#634]
# Bug Report

## Description

When sending multiple results with 'entered-in-error' to allow for full tally of total results, the interpretation of In Error values is included when determining coloration of the indicator.  These values were entered in error, and to our understanding, should not be considered clinically relevant to trigger coloration.

## Steps to Reproduce

1. Send multiple results, first being a result not entered in error.
2. Provide critical interpretation and status of 'entered-in-error' for one or more of the subsequent results.

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/43280824/77589418-a38aa900-6eb9-11ea-8774-649e47890a12.png)

## Expected Behavior
Numeric total is honored and displayed accordingly.  Interpretation for values marked as entered in error is ignored when determining coloration.

## Possible Solution
Allow status to be considered during [createEndAdditionalResultsStack](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx#L97).

## Environment

* Component Name and Version: terra-clinical-result 1.2.0 in FlowsheetResultCell 
* Browser Name and Version: Any
* Node/npm Version: N/A
* Webpack Version: N/A
* Operating System and version (desktop or mobile): N/A

**Comment by neilpfeiffer** [comment]
Validated as Bug in flowsheet-result-cell component where any additional result has both `status: 'entered-in-error'` and `interpretation: 'critical'` (or any that cause color change and adds high/critical class to stack with `additionalResultInterpretationIndicator`).


Potential fix (or similar):
For each additional result -- check for `isStatusInError` similar to [#L149](https://github.com/cerner/terra-clinical/blob/72930ec785901d3e8c52d5cdb28a491158a907f2/packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx#L149) before pushing interpretation to `additionalResultInterpretations` array for both results that are [single/standard (#L294-L295)](https://github.com/cerner/terra-clinical/blob/72930ec785901d3e8c52d5cdb28a491158a907f2/packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx#L294-L295) and in blood pressure, before pushing [systolic or diastolic (#L297-L300)](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx#L297-L300).

cc: @BenBoersma
