### ISSUE TITLE
[terra-clinical-result] In Error Blood Pressure Misalignment

### ISSUE THREAD

**Issue by PolymorphedSquirrel** [cerner/terra-clinical#635]
# Bug Report

## Description
Providing a normalcy other than normal to an in error systolic result value for a blood pressure results in misalignment of the In Error text.

## Steps to Reproduce

1. Provide non-normal interpretation and status 'entered-in-error' for the systolic component of a Blood Pressure within the FlowsheetResultCell.

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/43280824/77593465-3cbdbd80-6ec2-11ea-9d3a-cb0d14d7e60e.png)

## Expected Behavior
A blood pressure with a non-normal in error systolic result aligns with other result cell data.

## Environment

* Component Name and Version: terra-clinical-result 1.2.0 in FlowsheetResultCell 
* Browser Name and Version: Any
* Node/npm Version: N/A
* Webpack Version: N/A
* Operating System and version (desktop or mobile): N/A

**Comment by neilpfeiffer** [comment]
Validated as Bug in flowsheet-result-cell component where first result has both `status: 'entered-in-error'` and `interpretation: 'critical'` (or any with an icon) -- applies to both standard results and for blood pressure with a systolic result that adds an interpretation icon.

Potential fix (or similar):
[#L149](https://github.com/cerner/terra-clinical/blob/72930ec785901d3e8c52d5cdb28a491158a907f2/packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx#L149): `const isStatusInError = !isEmpty(status) ? checkIsStatusInError(status) : false;`
could be moved into `unpackResultAttributes` and update 
[#L228](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx#L228) to something like: 
`itemAttributes.interpretationIcon = !itemAttributes.statusInError && interpretationsWithIcons.includes(interpretation);`

cc: @BenBoersma
