### ISSUE TITLE
Multi Alpha values are displayed inline rather than on separate lines

### ISSUE THREAD

**Issue by ap056120** [cerner/terra-clinical#636]
## Description
Multi Alpha Values are ALL displayed inline, rather than on multiple lines.

## Steps to Reproduce

1.Fetch the [ClinicalResult](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-result/src/ClinicalResult.jsx) component from terra-clinical-result
2.Pass a result prop to the component an array of strings as the value sub-prop of result
eg: `<ClinicalResult result={{ value:['string', 'string', 'string'] }} />`
3. Render the above component
4. All the strings will be displayed inline with no period between them

## Additional Context / Screenshots
Multi Alphas Values are supposed to be displayed separately, each on its own line.

Current behavior:
![image](https://user-images.githubusercontent.com/36279874/77656285-a3ce8700-6f41-11ea-8189-27a700fc998f.png)

## Expected Behavior
I expect each element in an array of strings to be displayed in a line on its own.
Expected behavior:
![image](https://user-images.githubusercontent.com/36279874/77658992-7edc1300-6f45-11ea-81d5-c056e66aece8.png)

## Environment

* Component Name and Version: terra-clinical-result, v1.2.0
* Browser Name and Version: Chrome, v80.0.3987.149
* Node/npm Version: Node 8, npm 6
* Webpack Version: 4.42.1
* Operating System and version (desktop or mobile): MacOS, v10.15.3

**Comment by neilpfeiffer** [comment]
- For the standard terra-clinical-result component: update to have each item display on it's own new line.
- For flowsheet-result-cell component: if list is longer than one, show only the first item with an additional overflow display template "[...]" following the text, before the additional results stack.

**Comment by avinashg1994** [comment]
How do we handle this scenario, where value is passed as an array of strings, for clinical-result-blood-pressure component?
Should we only accept single strings to prevent this scenario, rather than array of strings?
@neilpfeiffer, your thoughts on this?
