### ISSUE TITLE
terra-clinical-header border lowlight is incorrect

### ISSUE THREAD

**Issue by hboege** [cerner/terra-clinical#654]
# Bug Report
When the fix was made in PR #649, it set the variable --terra-clinical-header-border-bottom to a color in lowlight.  But in the source code and the fusion theme, it is a border, for example: 1px solid #d3d4d5
I think the fact that the variable is not a proper border is keeping the border a light color when it needs to be dark.

## Description
Bottom border on terra-clinical-header is still not dark for a lowlight theme.

## Additional Context / Screenshots

<img width="317" alt="clinical-header" src="https://user-images.githubusercontent.com/30238809/80035835-513ba880-84b6-11ea-91e9-282f35631d76.png">

## Expected Behavior
Border should be darker in lowlight.

## Possible Solution
Update the lowlight variable to be a valid border value, like 1px solid #08090a

## Environment

* Component Name and Version:terra-clinical-header  3.17.0
* Browser Name and Version: Chrome
* Node/npm Version: [e.g. Node 8/npm 5] node 11
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by hboege** [comment]
I'm finding some other issues with our lowlight app, so the fact the border variable is defined inconsistently may not be the cause of the image attached.  However, it probably would still be good to get it consistent.

**Comment by mjhenkes** [comment]
I'm sorry, i really thought i fixed it :(

**Comment by hboege** [comment]
I did some more testing in the Chrome browser tools.  If I change the variable to something that is defined as a border, then the color is updated.  So the fact it is not a valid border seems like it might be causing our issue.
Is there any chance to get a correction this week?
