### ISSUE TITLE
[terra-clinical-data-grid] Update KeyCodes dependency

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#656]
# Feature Request

## Description
keycodes dependency is out-of-date and can be updated to v2
Looks like terra-clinical-data-grid was missed on the original issue logged to update to v2: https://github.com/cerner/terra-core/issues/2606

PR to reference: https://github.com/cerner/terra-core/pull/2616

## Additional Context / Screenshots

```
WARNING in keycode-js
  Multiple versions of keycode-js found:
    1.0.4 ./~/terra-clinical-data-grid/~/keycode-js
    2.0.3 ./~/keycode-js
```

**Comment by gabeparra01** [comment]
I can work on this task
