### ISSUE TITLE
Add Property to Hide Gridlines in Clinical Data Grid

### ISSUE THREAD

**Issue by cm9361** [cerner/terra-clinical#658]
# Feature Request

## Description
The Clinical Data Grid needs a property to allow consumers to hide gridlines

## Additional Context / Screenshots
N/A

## @ Mentions
@tbiethman

**Comment by neilpfeiffer** [comment]
Closing as Not a Supportable Feature by UX.

The Terra-clinical-data-grid was intentionally designed to create worklists, a specific type of complex tables, so the design and features of the data-grid are intentionally limited to provide a narrower set of capabilities than other similar basic Terra components (terra-table, etc.). 

I'll reach out to discuss your needs further and see if one of the other Terra components, perhaps like the extremely flexible [terra-cell-grid](https://engineering.cerner.com/terra-ui/components/terra-cell-grid/cell-grid/cell-grid), might be better suited to what you may be needing.
