### ISSUE TITLE
[terra-clinical-item-collection] terra-tag word wraps as endAccessory in small form factors

### ISSUE THREAD

**Issue by jvarness** [cerner/terra-clinical#681]
# Bug Report

## Description

I'm trying to use a [`terra-tag`](https://engineering.cerner.com/terra-ui/components/terra-tag/tag/tag) as the `endAccessory` of a [`terra-clinical-item-view`](https://engineering.cerner.com/terra-ui/components/terra-clinical-item-view/clinical-item-view/clinical-item-view), and there is a style that is causing a problem. There is a style in the clinical item view that appears to be forcing word wrapping within the tag when the view is tiny:

https://github.com/cerner/terra-clinical/blob/main/packages/terra-clinical-item-view/src/ItemView.module.scss#L39

## Steps to Reproduce

1. Create a `terra-tag` as an end accessory of an `ItemView` with some text.
2. On smaller views, the tag will word-wrap.

## Additional Context / Screenshots

When the collection is placed within a small window (about 250px or less), the `Tag` component will start to word-wrap it's text because of how small the allowed maximum width is:

<img width="1207" alt="Screen Shot 2020-07-22 at 12 03 02 PM" src="https://user-images.githubusercontent.com/6510879/88206224-8cfc2080-cc13-11ea-9774-c92d5dbb1da6.png">

## Expected Behavior

I would expect the `Tag` component to not word-wrap when added as an `endAccessory` to the `ItemCollection.Item` component.

## Possible Solution

I added a little scenario here that shows an example of the change we're trying to make in our code: https://github.com/jvarness/terra-clinical/commit/58d93a3c86e20ad9ae304b7418047554426db757

Would it be possible to remove the max-width of the accessory, or is there something we should do with our code to mitigate this for our use-case?

Removing the `max-width: 20%` appears to allow the `Tag` to grow to fit appropriately within the row:

<img width="1207" alt="Screen Shot 2020-07-22 at 12 05 44 PM" src="https://user-images.githubusercontent.com/6510879/88206366-c0d74600-cc13-11ea-9715-d3f79c609e6e.png">

## Environment

* Component Name and Version:
* Browser Name and Version: Chrome 84
* Node/npm Version: [e.g. Node 8/npm 5] Node 10
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by jvarness** [comment]
@emilyrohrbough @neilpfeiffer do you guys have any recommendations about this issue? Any insights you can provide would be extremely helpful. We could try to write our own styling that would eliminate the word-wrapping here, but I'd like to try and avoid custom styling as much as possible.

**Comment by neilpfeiffer** [comment]
Thanks @jvarness - even though it seems like a robust component, the terra-clinical-item-view has a very limited range of layout potential and was made as a very early/initial stop gap for some quick clinical lists on mobile. The start and end accessories particularly are not that flexible, as you have found that they are limited at a max-width of 20%, intended mainly just for icons. Removing the the max-width then creates a potential situation where the start and end content, if wide enough, could potentially squeeze the center item-view body content off until it is completely gone. 

Is there a particular design you are trying to achieve (I'm guessing the TBD tag isn't your intended end goal)? If so, I would recommend sharing it with me through internal communication and I can help you best determine how to approach it. Depending on your intended ui, I most likely will be recommending either dropping the tag or alternate component in to one of the items in the `displays` array, or create your own appropriate new list-item-layout component that will fit your design requirements in place of the clinical-item-view.

\
\
_nota bene:_ In this case, terra-tag is correctly responding/wrapping to the container it is being put inside of, attempting to best display the content given to it within the available space.  Adding your own custom styling on-top of the clinical-item-view that intentionally is overriding Terra provided styles is not recommended and not supported. Alternate approaches would be better and supportable.

**Comment by jvarness** [comment]
@neilpfeiffer will do, thank you for looking into this!

**Comment by neilpfeiffer** [comment]
Sounds great - thanks @jvarness. Closing this issue and will re-open new issue if needed, depending on what your design requirements will be after reviewing your ui options.
