### ISSUE TITLE
Create EmbeddedContentConsumer component to interface with embedded iframe content

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-clinical#70]
## Progress
- [ ] Design Input
- [ ] Expected Behaviour
- [ ] Tech Design
- [ ] Development
- [ ] Functional Validation
- [ ] UX Validation
- [ ] Released

------------------------------------------------------------

# Feature / Enhancement Request

Future React applications will need to embed iFrame content into themselves in order to present non-React content. However, we still want content in those embedded frames to communicate to their containing applications (using a messaging system like XFC) in order to drive workflows.

I would like to develop a generic EmbeddedContentConsumer component that will mount an iFrame within itself using XFC and handle the generated messages in a standard way.

## Expected Behavior

I have an (admittedly out of data) example in this branch: https://github.com/cerner/terra-clinical/blob/pdf_redux/packages/terra-clinical-application/src/patient-app/embedded-content-consumer/EmbeddedContentConsumer.jsx

Ideally, the EmbeddedContentConsumer (better names welcome :D) would have a simple prop API:
* `src` - The URL for the iFrame's `src` attribute
* `handlers` - An Object mapping message names to function handlers

When the EmbeddedContentConsumer mounts, it will mount the iFrame using XFC and establish communication with the Provider in the iFrame content. Then, when the Provider dispatches messages back to the EmbeddedContentConsumer, the EmbeddedContentConsumer will use the message name to lookup the proper handler from the `handlers` prop and will call the handler with the message payload as a parameter.

This would allow more opinionated components to wrap the EmbeddedContentConsumer and provide specific URLs and handlers. We may wish to include some default handlers in the EmbeddedContentConsumer itself, but I'm not sure what those defaults would be at this time.

The above linked branch also includes a EmbeddedContentProvider: https://github.com/cerner/terra-clinical/blob/pdf_redux/packages/terra-clinical-application/src/patient-app/embedded-content-provider/EmbeddedContentProvider.jsx

Theoretically, React content in the iFrame could be wrapped in that component and have the bootstrapping handled automatically. Non-React content would have to handle the bootstrapping separately (but in a similar way). I'm not sure a component like EmbeddedContentProvider is necessary at this time, but I'm documenting the prototype here to hopefully give everything a bit more context.

**Comment by tbiethman** [comment]
+1

**Comment by emilyrohrbough** [comment]
Closing this issue. This component was added to the terra-core repository in this PR https://github.com/cerner/terra-core/pull/737
