### ISSUE TITLE
Heroku PR deployed issue

### ISSUE THREAD

**Issue by windse7en** [cerner/terra-clinical#77]
## Summary
The Heroku review app can't be deployed due to the code size (after installing all npm modules, around 1.6 GB). It exceeds Heroku [slug size](https://devcenter.heroku.com/articles/limits#slug-size) after the compression.

The root cause is `terra-toolkit`(which is around 130 MB) has been installed repeatedly.

# Enhancement Request
Reorganize the source code and devDependencies to only import `terra-toolkit` once. 

## Expected Behavior
Only import `terra-toolki` once. Reduce the code size less than 1G.

**Comment by windse7en** [comment]
Leana provides a `--hoist` option for bootstrap, which can install common devDependencies only once in [link](https://github.com/lerna/lerna#--hoist-glob). By this way, we will install `terra-toolkit` only once.

But `terra-toolkit` relies on the relative location in the repo. In that case, we need to update `terra-tookit` to remove the relative path related code.

**Comment by emilyrohrbough** [comment]
Resolved in PR #80.
