### ISSUE TITLE
[Terra Clinical Onset Picker] disabled option

### ISSUE THREAD

**Issue by KunigundaLauly** [cerner/terra-clinical#809]
# Feature Request
Please add a disabled option to the Terra Clinical Onset Picker, as in the DatePickerField.

## Additional Context / Screenshots

https://engineering.cerner.com/terra-ui/components/terra-clinical-onset-picker/clinical-onset-picker/clinical-onset-picker
https://engineering.cerner.com/terra-ui/components/cerner-terra-framework-docs/date-picker/date-picker-field

**Comment by chrismichalewicz** [comment]
UXPLATFORM-6588 is created for internal tracking.

**Comment by KunigundaLauly** [comment]
up.

**Comment by chrismichalewicz** [comment]
@KunigundaLauly  We have an internal Jira logged for this so even if this github issue gets closed for being stale we will still include this request within our list of projects to prioritize for future work.
