### ISSUE TITLE
[clinical-onset-picker] Full width on mobile

### ISSUE THREAD

**Issue by KunigundaLauly** [cerner/terra-clinical#812]
# Feature Request
We have a design request, to make the datepicker fill up the width of the mobile view:
Current look:
![image](https://user-images.githubusercontent.com/47626274/170654718-b00a0094-e9f1-4274-ab37-a30e86918ae8.png)

Required look:
![image](https://user-images.githubusercontent.com/47626274/170654971-3797ab81-9bf0-4049-adb7-70925ea7d5df.png)

## Description

Please make the datepicker fill up the width on mobile view.
https://engineering.cerner.com/terra-ui/components/terra-clinical-onset-picker/clinical-onset-picker/clinical-onset-picker

**Comment by chrismichalewicz** [comment]
UXPLATFORM-6637  logged to track internally.
