### ISSUE TITLE
Investigate DRYing up the nightwatch.conf.js file between packages

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-clinical#82]
## Progress
- [ ] Design Input
- [ ] Expected Behaviour
- [ ] Tech Design
- [ ] Development
- [ ] Functional Validation
- [ ] UX Validation
- [ ] Released

# Feature / Enhancement Request
The nightwatch.conf.js file is repeated among all of the test directories in each package.  We should investigate using just one file.

**Comment by emilyrohrbough** [comment]
This investigation might be useful in solved issue #84.

**Comment by emilyrohrbough** [comment]
This has been accomplished in both terra-core (https://github.com/cerner/terra-core/pull/613) and terra-clinical (#150) when terra-toolkit was moved to its own repository.
