### ISSUE TITLE
terra-clinical-site should list terra-i18n-plugin as a devDependency

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-clinical#88]
# Issue Description

terra-clinical-site currently lists terra-i18n-plugin as a runtime dependency, this plugin should be listed as a devDependency instead. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

terra-clinical-site should build and deploy using terra-i18n-plugin as a devDependency 

## Current Behavior

N/A

See terra-core:
https://github.com/cerner/terra-core/blob/master/packages/terra-site/package.json#L83

**Comment by emilyrohrbough** [comment]
Resolved in #93
