### ISSUE TITLE
Ignore aggregated-translations

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-clinical#89]
# Issue Description

We should ignore aggregated-translations.

https://github.com/cerner/terra-clinical/tree/master/packages/terra-clinical-site/aggregated-translations
https://github.com/cerner/terra-clinical/blob/master/.gitignore#L53
https://github.com/cerner/terra-core/blob/master/.gitignore#L53
## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by emilyrohrbough** [comment]
Closed with #90
