### ISSUE TITLE
Error in running Nightwatch tests on a per-package basis 

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#9]
### Description of Issue
Terra-clinical nightwatch tests uses the terra-toolkit for the webpack configuration. Nightwatch tests cannot be ran for individual packages because the server-launcher default config-path is '../../terra-site/webpack.config', it results in the error:

> Error: Cannot find module '../../terra-site/webpack.config'

Each package needs updated to include a webpack_config_path so these tests can be run for each individual package.

### Steps to Reproduce the Issue
1. cd into package directory
2. npm run test:nightwatch-default

**Comment by mjhenkes** [comment]
resolved with pr #12
